services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:zech-chi
    ports:
      - "8080:443"
    restart: always
    networks:
      - inception_net
    volumes:
      - wordpress_volume:/var/www/html
    depends_on:
      - wordpress
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:zech-chi
    restart: always
    expose:
      - '3306'
    env_file:
      - .env
    networks:
      - inception_net
    # depends_on:
    #   - nginx
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:zech-chi
    env_file:
      - .env
    restart: always
    expose:
      - '9000'
    networks:
      - inception_net
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html
    
  static_website:
    container_name: static_website
    build: ./requirements/bonus/static_website
    image: static_website:zech-chi
    restart: always
    ports:
      - "8081:80"

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    image: adminer:zech-chi
    restart: always
    ports:
      - "8082:8080"
    networks:
      - inception_net

networks:
  inception_net:
    driver: bridge


volumes:
  mariadb_db:
    driver: local
    driver_opts:
        device: /tmp/inception_volumes/mariadb_volume14
        type: none
        o: bind
  wordpress_volume:
    driver: local
    driver_opts: 
      device: /tmp/inception_volumes/wordpress_volume14
      type: none
      o: bind