services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:zech
    ports:
      - "8080:443"
    restart: always
    # networks:
    #   - inception_net
    # depends_on:
    #   - wordpress
    #   - mariadb
  # wordpress:

  # mariadb: