services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    # networks:
    #   - inception_net
    # depends_on:
    #   - wordpress
    #   - mariadb
  # wordpress:

  # mariadb: