services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:zech-chi
    ports:
      - "443:443"
    restart: always
    networks:
      - inception_net
    volumes:
      - wordpress_volume:/var/www/html
    depends_on:
      - wordpress
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:zech-chi
    restart: always
    expose:
      - '3306'
    env_file:
      - .env
    networks:
      - inception_net
    volumes:
      - mariadb_db:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:zech-chi
    env_file:
      - .env
    restart: always
    expose:
      - '9000'
    networks:
      - inception_net
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html
    secrets:
      - wp_admin_password
      - wp_user_password
      - db_password

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    image: ftp:zech-chi
    env_file:
      - .env
    restart: always
    ports:
      - '21:21'
      - '40000-40100:40000-40100'
    networks:
      - inception_net
    volumes:
      - wordpress_volume:/home/zech-chi
    secrets:
      - ftp_password

  static_website:
    container_name: static_website
    build: ./requirements/bonus/static_website
    image: static_website:zech-chi
    restart: always
    ports:
      - "8081:80"

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    image: adminer:zech-chi
    restart: always
    ports:
      - "8082:8080"
    networks:
      - inception_net
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    image: redis:zech-chi
    restart: always
    ports:
      - "50000:6379"
    networks:
      - inception_net
    volumes:
      - wordpress_volume:/var/www/html

  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor
    image: cadvisor:zech-chi
    restart: always
    ports:
      - "8083:8080"
    networks:
      - inception_net
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro


networks:
  inception_net:
    driver: bridge



volumes:
  mariadb_db:
    driver: local
    driver_opts:
        device:  /home/zech-chi/data/mariadb_volume
        type: none
        o: bind
  wordpress_volume:
    driver: local
    driver_opts: 
      device:  /home/zech-chi/data/wordpress_volume
      type: none
      o: bind


secrets:
  ftp_password:
    file: ../secrets/ftp_password.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
